config/routes.rb
Rails.application.routes.draw do
  resources :consumptions
  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks"}
  resources :leftovers
  root to: "homepage#index"
  get 'homepage/search'
end

app/models/consumption.rb
class Consumption < ActiveRecord::Base
	belongs_to :leftover
end

app/models/leftover.rb
class Leftover < ActiveRecord::Base
	belongs_to :user
	has_many :consumption
	acts_as_mappable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]
  has_many :leftovers
  devise 

  def self.from_omniauth(auth)
  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    user.email = auth.info.email
    user.password = Devise.friendly_token[0,20]
    user.name = auth.info.name   # assuming the user model has a name
    user.profilepic = auth.info.image # assuming the user model has an image
  end
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/consumptions_controller.rb
class ConsumptionsController < ApplicationController
  before_action :set_consumption, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /consumptions
  # GET /consumptions.json
  def index
    #@consumptions = Consumption.all
     @geolocation = params[:geolocation].to_s.split(',')
     @leftovers = Leftover.within(5, :origin => @geolocation).where('current_quantity > 0')
     @consumption = Consumption.new
  end

  # GET /consumptions/1
  # GET /consumptions/1.json
  def show
  end

  # GET /consumptions/new
  def new
    @consumption = Consumption.new
  end

  # GET /consumptions/1/edit
  def edit
  end

  # POST /consumptions
  # POST /consumptions.json
  def create
    @consumption = Consumption.new(consumption_params)
    @consumption.user_id = current_user.id
    @c_leftover = @consumption.leftover
    @c_leftover.current_quantity = @c_leftover.current_quantity - @consumption.quantity
    if @c_leftover.current_quantity == 0
      @c_leftover.status = "Claimed"
    else 
      @c_leftover.status = "Available"
    end

    @c_leftover.save
    respond_to do |format|
      if @consumption.save
        format.html { redirect_to @consumption, notice: 'Consumption was successfully created.' }
        format.json { render :show, status: :created, location: @consumption }
      else
        format.html { render :new }
        format.json { render json: @consumption.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /consumptions/1
  # PATCH/PUT /consumptions/1.json
  def update
    respond_to do |format|
      if @consumption.update(consumption_params)
        format.html { redirect_to @consumption, notice: 'Consumption was successfully updated.' }
        format.json { render :show, status: :ok, location: @consumption }
      else
        format.html { render :edit }
        format.json { render json: @consumption.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /consumptions/1
  # DELETE /consumptions/1.json
  def destroy
    @consumption.destroy
    respond_to do |format|
      format.html { redirect_to consumptions_url, notice: 'Consumption was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_consumption
      @consumption = Consumption.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def consumption_params
      params.require(:consumption).permit(:leftover_id, :quantity, :user_id)
    end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
	before_action :authenticate_user!
	def index
	end
	def search
	end
end

app/controllers/leftovers_controller.rb
class LeftoversController < ApplicationController
  before_action :set_leftover, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /leftovers
  # GET /leftovers.json
  def index
    @leftovers = Leftover.all
  end

  # GET /leftovers/1
  # GET /leftovers/1.json
  def show
  end

  # GET /leftovers/new
  def new
    @leftover = current_user.leftovers.build
  end

  # GET /leftovers/1/edit
  def edit
  end

  # POST /leftovers
  # POST /leftovers.json
  def create
    @leftover = current_user.leftovers.build(leftover_params)
    @leftover.current_quantity =  @leftover.quantity
    @leftover.lat = @leftover.location.to_s.split(',')[0]
    @leftover.lng = @leftover.location.to_s.split(',')[1]
    respond_to do |format|
      if @leftover.save
        format.html { redirect_to @leftover, notice: 'Leftover was successfully created.' }
        format.json { render :show, status: :created, location: @leftover }
      else
        format.html { render :new }
        format.json { render json: @leftover.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /leftovers/1
  # PATCH/PUT /leftovers/1.json
  def update
    respond_to do |format|
      if @leftover.update(leftover_params)
        format.html { redirect_to @leftover, notice: 'Leftover was successfully updated.' }
        format.json { render :show, status: :ok, location: @leftover }
      else
        format.html { render :edit }
        format.json { render json: @leftover.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leftovers/1
  # DELETE /leftovers/1.json
  def destroy
    @leftover.destroy
    respond_to do |format|
      format.html { redirect_to leftovers_url, notice: 'Leftover was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_leftover
      @leftover = Leftover.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def leftover_params
      params.require(:leftover).permit(:title, :address, :location, :pincode, :quantity, :food_type, :available_from, :available_to, :status, :user_id)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/consumptions_helper.rb
module ConsumptionsHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/leftovers_helper.rb
module LeftoversHelper
end

app/views/consumptions/_form.html.erb
<%= form_for(@consumption) do |f| %>
  <% if @consumption.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@consumption.errors.count, "error") %> prohibited this consumption from being saved:</h2>

      <ul>
      <% @consumption.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :leftover_id %><br>
    <%= f.number_field :leftover_id %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/consumptions/edit.html.erb
<h1>Editing Consumption</h1>

<%= render 'form' %>

<%= link_to 'Show', @consumption %> |
<%= link_to 'Back', consumptions_path %>

app/views/consumptions/index.html.erb
<div class="body-content">
<div class="row">
<% if @leftovers.any? %>
<div class="content active">
<h1>We've found food near you !</h1>

<table class="table table-striped" id="foodAvailable">
  <thead>
    <tr>
      <th>Title</th>
      <th>Address</th>
      <th>Food type</th>
      <th>Quantity</th>
      <th>Available from</th>
      <th>Available to</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @leftovers.each do |leftover| %>
      <tr>
        <td><%= leftover.title %></td>
        <td><%= leftover.address %></td>
        <td><%= leftover.food_type %></td>
        <td class="food_quantity"><%= leftover.current_quantity %></td>
        <td><%= leftover.available_from %></td>
        <td><%= leftover.available_to %></td>
        <td>
          <%= form_for(@consumption) do |f| %>
          <%= f.number_field :quantity, :class => 'input_qty' %>
          <%= f.hidden_field :leftover_id,:value => leftover.id   %>
          <%= f.submit 'Reserve', :class => 'btn btn-primary '  %>
          <% end %>
          
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<% else %>
<div class="content active">
<h2>Sorry, no shared food around you.</h2>
</div>
<% end %>
</div>
</div>

app/views/consumptions/new.html.erb

<h1>New Consumption</h1>

<%= render 'form' %>

<%= link_to 'Back', consumptions_path %>

app/views/consumptions/show.html.erb
<div class="body-content">
<div class="content active">
<h2>Yay..! Your food is ready at <%=@consumption.leftover.address %><h2>

<%= link_to 'Back', root_path , :class => 'btn btn-primary MarginTop10Px'  %>
</div>

app/views/homepage/index.html.erb
<div class="body-content">
<div class="col-sm-8 col-sm-offset-2 content-text">
<h1 class="center"> Share, don't waste. </h1>
<!-- <p>Save food and spread love: Spread the love - share the app with your friends<br>
Score free food from you neighbourhood <br>
Have some “good” food leftover? share them<br>
Why sleep hungry tonight? look for freebies in your own suburb<br>
Don’t waste food. There is someone else sleeping hungry tonight<br>
Share you dinner/ lunch or breakie!</p>
</div> -->
<h4> Bought too much? Have left over food? We believe you could share it instead of throwing it in the bin.</h4>
<ul >
<li>4,000,000 tonnes of food each year is wasted in Australia. Thats $8 billion.</li>
<li>&gt;20% of fruits and vegetables are rejected</li>
<li>Best-before is different to use-by</li>
</ul>

<div class="row demo-tiles" >
	<div class="col-xs-6">
		<div class="tile">
			<%= image_tag "green-shopping-bag-pv.png", :alt => "Share Food", :class => "tile-image" %>
			<%= link_to 'I have some food to share', new_leftover_path, :class=>"btn btn-primary btn-large btn-block" %> 
		</div>
	</div>
	<div class="col-xs-6">
		<div class="tile">
			<%= image_tag "glass-icon-food-beverage-knife-fork3.png", :alt => "Share Food", :class => "tile-image" %>
			<%= link_to "I'd like some food please", homepage_search_path, :class=>"btn btn-primary btn-large btn-block" %> 
		</div>
	</div>

</div>
 </div>
 </div>

app/views/homepage/search.html.erb
<script type="text/javascript">
	$(function(){
		$("#search-geo-location").click(function(){
			//alert($("#geo-latlng").val())
			window.location.href = "http://localhost:3000/consumptions?geolocation="+$("#geo-latlng").val();
		})
	})
      var placeSearch, autocomplete;
      function initAutocomplete() {
        autocomplete = new google.maps.places.Autocomplete(
            (document.getElementById('autocomplete')),
            {types: ['geocode']});

        autocomplete.addListener('place_changed', fillInAddress);
      }

      function fillInAddress() {
        var place = autocomplete.getPlace();
        $("#geo-latlng").val(place.geometry.location.lat()+","+place.geometry.location.lng())
      }
      function geolocate() {
        if (navigator.geolocation) {
          navigator.geolocation.getCurrentPosition(function(position) {
            var geolocation = {
              lat: position.coords.latitude,
              lng: position.coords.longitude
            };
            var circle = new google.maps.Circle({
              center: geolocation,
              radius: position.coords.accuracy
            });
            autocomplete.setBounds(circle.getBounds());
          });
        }
      }
</script>

<div class="body-content">
<div class="row">
<div class="content active">
<h1>Where are you now ?</h1>
<input type="text" id="autocomplete" class="form-control" onfocus="geolocate()" autocomplete="off"></input>
<input type="hidden" id="geo-latlng" value=""></input>

<a href="#" id="search-geo-location" class="btn btn-lg btn-primary MarginTop10Px">Search</a>

</div>
</div>
</div>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDWYH9z0PIhnBdttHJF6adA8GjuhY0LDao&libraries=places&callback=initAutocomplete"></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hot Potatoe</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">

<div class="container">
	<% if user_signed_in? %>
	<div class="pull-right">
	  	<div class="profile-info">
			<div class="profile-image"><img src=<%= current_user.profilepic %>></div>
			<div class="profile-name"><%= current_user.name %></div>
	  	</div>
	</div>
	<% end %>
</div>


<%= yield %>
</div>
</body>
</html>

app/views/leftovers/_form.html.erb
<%= form_for(@leftover) do |f| %>
  <% if @leftover.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@leftover.errors.count, "error") %> prohibited this leftover from being saved:</h2>

      <ul>
      <% @leftover.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="content active">
<%= f.label :title %><br>
    <%= f.text_field :title , :class => 'form-control'%> 
   <br>
    <%= f.label :address %><br>
    <%= f.text_field :address, :id => 'autocomplete' , :onfocus => 'geolocate()', :autocomplete => 'off', :class => 'form-control' %>

    <%= f.hidden_field :location , :id => 'location', :class => 'form-control'%>
    <a href="#" class="btn btn-primary next_btn MarginTop10Px">Next</a>
    <%= link_to 'Back', leftovers_path, :class => "btn btn-primary next_btn MarginTop10Px pull-right" %>
</div>
<div class="content">
  <%= f.label :food_type %><br>
  <%= f.text_field :food_type , :class => 'form-control'%>
  <br>
  <%= f.label :quantity %><br>
  <%= f.number_field :quantity , :class => 'form-control'%>
  <a href="#" class="btn btn-primary next_btn MarginTop10Px">Next</a>
  <%= link_to 'Back', leftovers_path, :class => "btn btn-primary next_btn MarginTop10Px pull-right" %>
</div>
<div class="content">
    <%= f.label :available_from %><br>
    <%= f.text_field :available_from , :class => 'form-control'%>
    <br/>
    <%= f.label :available_to %><br>
    <%= f.text_field :available_to , :class => 'form-control'%>  
    <%= f.submit 'Donate', :class => 'btn btn-primary MarginTop10Px'  %>
    <%= link_to 'Back', leftovers_path, :class => "btn btn-primary next_btn MarginTop10Px pull-right" %>
</div>
  </div>
 
  <div class="field">
    
  </div>
  <div class="field">
    
    
  </div>
  
  <div class="actions">
  </div>
<% end %>
<script type="text/javascript">
  $(function(){
      $(".next_btn").click(function(){
    var parent = $(this).parent()
    parent.fadeThenSlideToggle();
    parent.next('.content').fadeThenSlideToggle()
  })
  
  jQuery.fn.fadeThenSlideToggle = function(speed, easing, callback) {
  if (this.is(":hidden")) {
    return this.slideDown(speed).fadeTo();
  } else {
    return this.fadeTo().slideUp(speed);
    
  }
};
  })
</script>

app/views/leftovers/edit.html.erb
<h1>Editing Leftover</h1>

<%= render 'form' %>

<%= link_to 'Show', @leftover %> |
<%= link_to 'Back', leftovers_path %>

app/views/leftovers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Leftovers</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Address</th>
      <th>Food type</th>
      <th>Quantity</th>
      <th>Available from</th>
      <th>Available to</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @leftovers.each do |leftover| %>
      <tr>
        <td><%= leftover.title %></td>
        <td><%= leftover.address %>, <%= leftover.pincode %></td>
        <td><%= leftover.food_type %></td>
        <td><%= leftover.current_quantity %></td>
        <td><%= leftover.available_from %></td>
        <td><%= leftover.available_to %></td>
        <td><%= leftover.status %></td>
        <td><%= link_to 'Show', leftover %></td>
        <td><%= link_to 'Edit', edit_leftover_path(leftover) %></td>
        <td><%= link_to 'Destroy', leftover, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Leftover', new_leftover_path %>

app/views/leftovers/new.html.erb
 <div class="modal fade" id="terms_and_conditions" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Terms and Conditions</h4>
        </div>
        <div class="modal-body">
          <p>All participants are responsible for making they share food that is not spoilt, not expired, not contaminated</p>
          <p>All participants are responsible mentioning your product clearly, with the right name, ingredients and contents</p>
          <p>All participants are responsible mentioning the right expiry date</p>
          <p>HotPotatoe is not responsible for any food that is shared or received</p>
          <p>HotPotatoe is not liable/responsible for the user’s safely or any legal obligation</p>
          <p>This app is intended for a social-cause to avoid excess wastage of “good” “edible” food</p>
          </p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-primary" data-dismiss="modal">Accept</button>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal --> 

<div class="body-content">
<div class="row">
<div class="">
<%= render 'form' %>
</div>
</div>
</div>
<script type="text/javascript">
      $(function(){
      	$('#terms_and_conditions').modal('show');
      })
      var placeSearch, autocomplete;
      function initAutocomplete() {
        autocomplete = new google.maps.places.Autocomplete(
            (document.getElementById('autocomplete')),
            {types: ['geocode']});

        autocomplete.addListener('place_changed', fillInAddress);
      }

      function fillInAddress() {
        var place = autocomplete.getPlace();
        $("#location").val(place.geometry.location.lat()+","+place.geometry.location.lng())
      }
      function geolocate() {
        if (navigator.geolocation) {
          navigator.geolocation.getCurrentPosition(function(position) {
            var geolocation = {
              lat: position.coords.latitude,
              lng: position.coords.longitude
            };
            var circle = new google.maps.Circle({
              center: geolocation,
              radius: position.coords.accuracy
            });
            autocomplete.setBounds(circle.getBounds());
          });
        }
      }
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDWYH9z0PIhnBdttHJF6adA8GjuhY0LDao&libraries=places&callback=initAutocomplete"></script>

app/views/leftovers/show.html.erb
<div class="body-content">
<div class="content active">
<div class="alert alert-success" role="alert">You're Awesome.. We'll let people know you have leftovers</div>
<p>
  <strong>Title:</strong>
  <%= @leftover.title %>
</p>

<p>
  <strong>Address:</strong>
  <%= @leftover.address %>
</p>
<p>
  <strong>Quantity:</strong>
  <%= @leftover.quantity %>
</p>

<p>
  <strong>Food type:</strong>
  <%= @leftover.food_type %>
</p>

<p>
  <strong>Available from:</strong>
  <%= @leftover.available_from %>
</p>

<p>
  <strong>Available to:</strong>
  <%= @leftover.available_to %>
</p>

<%= link_to 'Edit', edit_leftover_path(@leftover) , :class => 'btn btn-primary MarginTop10Px'  %>
<%= link_to 'Go back', root_path , :class => 'btn btn-primary MarginTop10Px'  %>
</div>
</div>